site_name: Patcherex2 Docs

theme:
  name: "material"
  features:
    - search.suggest

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: sphinx
  - search


nav:
  - index.md
  - Examples: examples.md
  - Reference: reference.md